def func(a):
    print(len(a))
    print(a.isupper())
    print(a.islower())
    print(a.upper())
    print(a.lower())
    print(a.capitalize())
    print(a.title())
    print(a.isalpha())
    print(a.isdigit())
    print(a.isalnum())
